# =============================================================================
# RENDER BLUEPRINT - FLOW-FORGE API
# =============================================================================
# Este arquivo configura deploy automático no Render
# Docs: https://render.com/docs/blueprint-spec
# =============================================================================

services:
  # Web Service - API Node.js
  - type: web
    name: flow-forge-api
    runtime: node
    region: oregon # ou frankfurt para Europa
    plan: free # Upgradable to paid plans

    # Build Configuration
    buildCommand: npm install --production
    startCommand: node ./bin/www

    # Health Check
    healthCheckPath: /health

    # Environment Variables (configure no Dashboard ou aqui)
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000 # Render usa porta 10000 por padrão

      # MongoDB - Configure no Dashboard (Sensitive)
      - key: MONGODB_URI
        sync: false # Definir manualmente no dashboard

      # JWT Secrets - Configure no Dashboard (Sensitive)
      - key: JWT_SECRET
        sync: false

      - key: JWT_REFRESH_SECRET
        sync: false

      - key: JWT_EXPIRES_IN
        value: 1h

      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000

      - key: RATE_LIMIT_MAX_REQUESTS
        value: 1000

      # CORS
      - key: ALLOWED_ORIGINS
        sync: false # Configure com seus domínios

      # Trust Proxy
      - key: TRUST_PROXY
        value: true

      # Google OAuth (Opcional)
      - key: GOOGLE_CLIENT_ID
        sync: false

      - key: GOOGLE_CLIENT_SECRET
        sync: false

      - key: GOOGLE_REDIRECT_URI
        sync: false

      - key: FRONTEND_URL
        sync: false

      # Google API Key (Opcional)
      - key: GOOGLE_API_KEY
        sync: false

      # Encryption Key
      - key: ENCRYPTION_KEY
        sync: false

      # SMTP (Opcional)
      - key: SMTP_HOST
        value: smtp.gmail.com

      - key: SMTP_PORT
        value: 587

      - key: SMTP_SECURE
        value: false

      - key: SMTP_USER
        sync: false

      - key: SMTP_PASS
        sync: false

# =============================================================================
# NOTAS IMPORTANTES:
# =============================================================================
#
# 1. DEPLOY:
#    - Conecte este repo no Render Dashboard
#    - Render detectará este arquivo automaticamente
#    - Configure as variáveis sensíveis (sync: false) no Dashboard
#
# 2. MONGODB:
#    - Use MongoDB Atlas ou similar
#    - Render não oferece MongoDB grátis (apenas PostgreSQL)
#
# 3. CRON JOBS:
#    - Adicione cron jobs no Dashboard após deploy
#    - Ou use o scheduler interno da aplicação (já funciona!)
#
# 4. WEBSOCKETS:
#    - Funcionam perfeitamente no Render
#    - Socket.io rodará sem problemas
#
# 5. FREE TIER:
#    - App dorme após 15min inatividade
#    - Acorda automaticamente com primeira request (5-30s)
#    - 750 horas/mês grátis
#
# =============================================================================